<?php

/**
 *      [Discuz!] (C)2001-2099 Comsenz Inc.
 *      This is NOT a freeware, use is subject to license terms
 *
 *      $Id: lang_template.php 33227 2013-05-07 11:23:50Z jeffjzhang $
 *
 *      This file is automatically generate
 */

$lang = array (
  'no_simplemobiletype'   => 'Standard Edition',//'标准版',
  'nomobiletype'      => 'PC Edition',//'电脑版',
  'simplemobiletype'    => 'Simple Edition',//'精简版',
  'extremelysimplemobiletype' => 'Minimalist version',//'极简版',
  'favorite'      => 'Favorites',//'收藏',
  'my_posts'      => 'My posts',//'我的帖子',
  'new_pm'      => 'New PM',//'新短消息',
  'waptitle'      => 'Mobile',//'手机版',
  'login_mobile'      => 'Log in now - {$_G[setting][bbname]} Mobile',//'现在就登录 - {$_G[setting][bbname]} 手机版',
  'login_mobile_join'   => 'Now use the phone to access, access to fast mobile experience',//'立即使用手机访问，获得极速移动体验',
  'mobile_favorite'   => 'Quick Add Favorites',//'快速收藏',
  'mobile_favorite_comment' => 'You can quick acces to forum by phone and manage your favorites. Access your favorite content anytime, anywhere.',//'您可以通过手机快速访问论坛版块及管理收藏夹，随时随地访问自己最爱的内容',
  'mobile_other_1'    => 'Save traffic and access to quality mobile experience co-exist',//'节省流量与获得优质手机体验并存',
  'mobile_pm'     => 'Send and receive messages in real-time, chat with one or more friends.',//'站内短信实时收发，与短信另一端的朋友进行单人或多人聊天',
  'mobile_viewthread'   => 'View posts and replies faster',//'看帖及回帖更快速',
  'mobile_viewthread_comment' => 'Through the mobile phone version, you can quick access to read threads, and can quickly publish new posts and replies',//'通过手机版，可以快速的访问您需要阅读的主题，并可以快速的发布新帖及回复',
  'continue'      => 'Continue',//'继续访问',
  'goback'      => 'Back',//'返回上一页',
  'message_forward_mobile'  => 'Click here to forward',//'点击此链接进行跳转',
  'favorite_delete'   => 'Remove Favorites',//'取消收藏',
  'index_members'     => 'Members',//'会员',
  'index_today'     => 'Today',//'今日',
  'my_favorites_forums'   => 'My Favorite Forums',//'我收藏的版块',
  'online'      => 'Online',//'在线',
  'sourceimagesize'   => 'Original Size',//'原图尺寸',
  'forum_posts'     => 'Replies',//'回',
  'group'       => 'Group',//'群',
  'post_newthreaddebate'    => 'New debates',//'发辩论',
  'post_newthreadpoll'    => 'New polls',//'发投票',
  'post_newthreadreward'    => 'New rewards',//'发悬赏',
  'send_threads'      => 'Post',//'发帖',
  'thread_digest'     => 'Digest',//'精',
  'thread_recommend'    => 'Recommend',//'荐',
  'thread_sticky'     => 'Stick',//'顶',
  'threadsort'      => 'Thread category',//'分类信息',
  'threadtype'      => 'Thread type',//'主题分类',
  'viewnewthread'     => 'New thread',//'新帖排序',
  'admin_threadtopicadmin_error'  => 'Mobile Edition does not support complex management operations',//'手机版不支持复杂管理操作',
  'expiry'      => 'Time <span class="xg2">(0 for permanent / 1 is 1 day)</span>',//'期限<span class="xg2">(0为永久/1为1天)</span>',
  'mod_message_goto_admincp'  => 'Require you use your computer browser to access the advanced features of the background operation',//'需要您使用电脑浏览器进入后台进行高级功能操作',
  'result'      => 'Search results',//'查找结果',
  'join_thread'     => 'Join thread',//'回复',
  'required'      => 'Required',//'必填',
  'send_special_activity_error' => 'Mobile does not support <strong>activity</strong> adding, please click on the top post for choose other way',//'手机版不支持<strong>活动</strong>发布，请点击上方发帖选择其他方式',
  'send_special_trade_error'  => 'Mobile does not support <strong>products</strong> adding, please click on the top post for choose other way',//'手机版不支持<strong>商品</strong>发布，请点击上方发帖选择其他方式',
  'threadsort_error'    => 'For publish category info, use the computer version',//'发布分类信息请使用电脑版',
  'threadsort_calendar'   => 'Date format :2010-12-31',//'日期格式：2010-12-01',
  'post_poll_options'   => 'Poll options',//'投票选项',
  'admin_close_expire_comment'  => '<span class="xg1">Optional date format :2010-12-31 10:50</span>',//'<span class="xg1">选填日期格式：2010-12-01 10:50</span>',
  'admin_delthread_confirm' => 'Are you sure you want to delete the thread?',//'您确认要删除？',
  'topicadmin_mobile_mod'   => 'Topic action mobile version',//'手机版主题操作',
  'admin_banpost_confirm'   => 'Are you sure to ban this post?',//'您要进行屏蔽操作',
  'admin_delpost_confirm'   => 'Are you sure you want to delete this reply?',//'您确定要删除此回复？',
  'admin_warn_confirm'    => 'Alerts the author that you want to warn',//'您要进行警告操作',
  'attach_nopermission_login' => 'You need to <a href="member.php?mod=logging&action=login">Login</a> for download or view attachments. No account yet? <a href="member.php?mod={$_G[setting][regname]}" title="Register">Register</a>',//'您需要<a href="member.php?mod=logging&action=login">登录</a>才可以下载或查看附件。没有帐号？<a href="member.php?mod={$_G[setting][regname]}" title="注册帐号">{$_G[setting][reglinkname]}</a>',
  'attachlist'      => 'Attachment list',//'附件列表',
  'ban_member'      => 'Ban',//'禁止',
  'digest'      => '<span class="xi1">Digest</span>',//'<span class="xi1">精华</span>',
  'forum_views'     => 'Views',//'看',
  'send_pm'     => 'Send PM',//'发消息',
  'thread_show_all'   => 'See all',//'看全部',
  'thread_show_author'    => 'Look at him',//'只看他',
  'activity_mod'      => 'Please use the non-mobile version for manage your activities',//'请您使用非手机版管理活动',
  'poll_msg_allwvote_user'  => 'You need to <a href="member.php?mod=logging&action=login">Login</a> for vote the poll',//'您需要<a href="member.php?mod=logging&action=login">登录</a>之后方能进行投票',
  'resolved'      => 'Resolved',//'已解决',
  'unresolved'      => 'Unresolved',//'未解决',
  'trade_mod'     => 'Please use the non-mobile version for manage product',//'请您使用非手机版管理商品',
  'my_favorites_thread'   => 'My Favorite Threads',//'我收藏的帖子',
  'return_forum'      => 'Back to Forum',//'返回论坛',
  'title_memcp_favorite'    => 'Favorites',//'收藏',
  'back'        => 'Back',//'返回',
  'chatpm'      => 'Group chat',//'群聊',
  'chatpm_author'     => 'Author',//'发起者',
  'pm_totail'     => 'PMs',//'交谈',
  'pm_with'     => 'with',//'与',
  'user_mobile_pm_error'    => 'Mobile PM does not support complex operations, return to <a href="home.php?mod=space&do=pm&filter=privatepm">My PM</a>',//'手机版不支持复杂短消息操作，请返回<a href="home.php?mod=space&do=pm&filter=privatepm">我的短消息</a>',
  'basic_information'   => 'Basic info',//'基本资料',
  'favorite_description_default'  => 'Mobile Favorites',//'手机收藏',
  'favorite_forum_confirm'  => 'Add this forum:',//'收藏此版块: ',
  'favorite_thread_confirm' => 'Add this thread:',//'收藏此主题: ',
  'user_mobile_pm_comment'  => 'After the messages sent you will returned to previous page',//'短消息发出后将跳回上一页',
  'reset'       => 'Reset',//'重填',
  'reg_username'      => 'User name length must be in a range of 3-15 characters',//'用户名必须为大于3位小于15位',
  'empty'       => 'There are no posts',//'没有帖子',
  'mobilehome'      => 'Home',//'首页',
  'register'      => 'Register',//'注册',
  'mobile2version'    => 'Touch-screen version',//'触屏版',
  'clientversion'     => 'Client',//'客户端',
  'forum_list'      => 'Forum List',//'版块列表',
  'user_info'     => 'User Info',//'用户信息',
  'hot_thread'      => 'Hot threads',//'热帖',
  'send_reply_fast_tip'   => 'I want to say too',//'我也说一句',
  'nologin_tip'     => 'You are not logged, Sign in now?',//'您还未登录，立即登录?',
  'nopostreply'     => 'No permission to reply',//'您暂时没有权限发表',
  'hotest_thread'     => 'Top hot threads',//'精彩热帖',
  'send_thread'     => 'Publish',//'发表',
  'thread_subject'    => 'Title',//'标题',
  'thread_content'    => 'Content',//'内容',
  'uploadpicfailed'   => 'Upload failed, please try again later',//'上传失败，请稍后再试',
  'uploadpicatttypeban'   => '(Attachment type is disabled)',//'(附件类型被禁止)',
  'donotcross'      => '(Can not exceed ',//'(不能超过',
  'bytemore'      => ' bytes)',//'字节)',
  'networkerror'      => 'Network problems, please try again later',//'网络出现问题，请稍后再试',
  'viewonlyauthorid'    => 'Only for author',//'只看楼主',
  'recommend_post'    => 'Recommend',//'推荐',
  'numheader'     => 'No.',//'第',
  'unitpaper'     => 'pages',//'张',
  'numtotal'      => 'Total',//'共',
  'lastpic'     => 'Last image',//'最后一张',
  'firstpic'      => 'First image',//'第一张',
  'favforum'      => 'Favorite forums',//'收藏版块',
  'favthread'     => 'Favorite threads',//'收藏帖子',
  'viewmypm'      => 'View PM',//'查看消息',
  'myprofile'     => 'My profile',//'我的资料',
  'otherprofile'      => 'Other info',//'的资料',
  'logout_mobile'     => 'Log out',//'退出登录',
  'myfavorite'      => 'My Favorites',//'我的收藏',
  'mythread'      => 'My threads',//'我的主题',
  'mypm'        => 'My PM',//'我的消息',
  'sendpm'      => 'Send',//'发送',
  'inputyourname'     => 'Please enter your user name',//'请输入用户名',
  'useqqconnectlogin'   => 'or use QQ for login',//'或使用QQ登录',
  'noregister'      => 'Yet not registered?',//'还没有注册？',
  'registerinputtip'    => 'User Name: 3-15 characters',//'用户名：3-15位',
  'registerpassword2'   => 'Confirm Password',//'确认密码',
  'registeremail'     => 'E-Mail',//'邮箱',
  'quickregister'     => 'Register Now',//'立即注册',
  'searchthread'      => 'Search threads',//'搜索帖子',
  'uploadstatusmsgnag1'   => 'Internal Server Error',//'内部服务器错误',
  'uploadstatusmsg0'    => 'Uploaded successfully',//'上传成功',
  'uploadstatusmsg1'    => 'Such extension is not supported',//'不支持此类扩展名',
  'uploadstatusmsg2'    => 'The attachment exceeds the server limit, can not upload',//'服务器限制无法上传那么大的附件',
  'uploadstatusmsg3'    => 'The attachment exceeds the group limit, can not upload',//'用户组限制无法上传那么大的附件',
  'uploadstatusmsg4'    => 'Such extension is not supported',//'不支持此类扩展名',
  'uploadstatusmsg5'    => 'The attachment exceeds the file type limit, can not upload',//'文件类型限制无法上传那么大的附件',
  'uploadstatusmsg6'    => 'Today you can not upload attachments',//'今日您已无法上传更多的附件',
  'uploadstatusmsg7'    => 'Please select the image file',//'请选择图片文件',
  'uploadstatusmsg8'    => 'The attachment file can not be saved',//'附件文件无法保存',
  'uploadstatusmsg9'    => 'No valid files being uploaded',//'没有合法的文件被上传',
  'uploadstatusmsg10'   => 'Illegal operation',//'非法操作',
  'uploadstatusmsg11'   => 'Today you can not upload so much attachments',//'今日您已无法上传那么大的附件',
  'postreplyneedmod'    => 'Forum posts need to be verified. Your post will be displayed only after auditing by a moderator.',//'本版回帖需要审核，您的帖子将在通过审核后显示',
  'replylist'     => 'Reply list',//'回复列表',
  'last_thread'     => 'Previous thread',//'上一个主题',
  'next_thread'     => 'Next trhread',//'下一个主题',
  'warmtip'     => 'Warm tip',//'温馨提示',
  'zsltmobileclient'    => 'Mobile forum client',//'掌上论坛手机客户端',
  'visitbbsanytime'   => 'Visit the forum anytime and anywhere',//'随时随地上论坛',
  'clicktodownload'   => 'Click to download',//'点击下载',
  'iphoneandriodmobile'   => 'iPhone, Andriod and other smartphones',//'iPhone,Andriod等智能手机',
  'visitwapmobile'    => 'Log in directly to the mobile version, Reading experience better',//'直接登录手机版，阅读体验更佳',
  'clicktovisitwapmobile'   => 'Access the Mobile version',//'访问手机版',
  'downloadnow'     => 'Download Now',//'立即下载',
  'downloadzslttoshareview' => 'Download the new version of Mobile Forum Client, Enjoy the lot of new privileges!',//'下载新版掌上论坛客户端，尊享多项看帖特权!',

  'forum' => 'forum',//论坛版块
  'get' => 'get',//获取
  'more-forums' => 'more forums',//查看更多版块
  'offical-service' => 'offical service',//官方服务
  'gift' => 'gift',//游戏礼包
  'game-videos' => 'game videos',//游戏视频
  'more' => 'more',//更多
  'pc-edition' => 'PC Edition',//电脑版
  'favorites' => 'Favorites',//收藏本版
  'post' => 'Post',//我要发帖
  'subforums' => 'sub-forums',//子版块
  'piclist' => 'PicList',//图
  'list' => 'List',//文
  'all-theme' => 'all',//全部主题
  'default' => 'default',//默认
  'lastest' => 'latest',//最新
  'hot' => 'hot',//热门
  'recommend' => 'recommend',//精华
  'top' => 'top',//置顶
  'author' => 'author',//作者
  '1sago' => '1s ago',//秒前
  '1minago' => '1min ago',//分钟前
  'daybefore' => 'day before',//天前
  'there-is-no-data' => 'there is  no data~',//没有数据了哦~
  'add-my-comment' => 'add my comment',//我也来说一句吧
  'reply' => 'reply',//回复
  'first' => 'first',//第
  'pages' => 'pages',//页
  'current' => 'current',//当前
  'reorder-them-by-dragging-pics' => ' reorder them by dragging pics',//图片可以拖动排序
  'first-floor-what-if-im-popular' => "first floor!what if I'm popular",//前排占个座#17,万一火了呢#89
  'be-the-first' => 'be the first',//抢个前排
  'it-sounds-good' => 'it sounds good',//楼猪说的真好#81给楼猪点赞啦#44
  'i-support-you' => 'I support you',//好文要顶
  'you-look-like-a-bad' => 'you look like a bad',//虽然不知道楼猪在说什么#24，但是看起来好厉害的样子！
  'its-amazing' => "it's amazing!",//不明觉厉
  'life-is-hard' => 'life is hard', //人艰不拆
  'life-is-already-hard-so-dont-expose-the-truth' => "Life is already hard , so don't expose the truth !",//人生已经如此艰难，有些事情就不要拆穿#135
  'watering' => 'watering',//小手一抖，酱油到手，积分我有#163
  'im-just-having-a-look' => "I'm just having a look",//小手一抖小手一抖
  'uploading' => 'uploading…',//上传中
  'success' => 'success',//发表成功
  'show-the-authors-posts-only' => "show the author's posts only",//只看该作者
  'manage' => 'manage',//管理
  'edit' => 'edit',//编辑
  'delete' => 'delete',//删除
  'open' => 'open',//打开
  'close' => 'close',//关闭
  'shield' => 'shield',//屏蔽
  'warning' => 'warning',//警告
  'are-you-sure-to-delete' => 'are you sure to delete?',//你确认要删除
  'submit' => 'submit',//确定
  'cancel' => 'cancel',//取消
  'valid-for-date' => 'Valid for (date)',//有效期（不填则永久有效）
  'close-the-post' => 'close the post',//关闭主题
  'open-the-post' => 'open the post',//打开主题
  'you-are-going-to-block-the-content' => 'you are going to block the content',//您要进行屏蔽操作
  'you-are-going-to-warn-the-author' => 'you are going to warn the author',//您要进行警告操作
  'successful' => 'successful',//管理操作成功
  'post-blocked-by-administrator-only-can-view' => 'the post is blocked by administrator and only administrators can view',//该帖被管理员或版主屏蔽，只有管理员或有管理权限的成员可见
  'tips' => 'tips',//提示
  'post-is-blocked-by-administrator' => 'the post is blocked by administrator',//该帖被管理员或版主屏蔽
  'be-warned' => 'be warned',//受到警告
  'share' => 'share',//分享
  'collect' => 'collect',//收藏
  'like' => 'like',//点赞
  'recommend' => 'recommend',//推荐
  'sofa' => 'sofa',//沙发
  'chair' => 'chair',//板凳
  'bench' => 'bench',//地板
  'multiple-votes' => 'multiple votes',//多选投票
  'single-vote' => 'single vote',//单选投票
  'items' => 'items',//项
  'votes' => 'votes',//票
  'at-most'=> 'at most',//最多
  'people-vote' => 'people vote',//人参与投票
  'from-ending' => 'from ending',//距离结束还有
  'day' => 'day',//天
  'hour' => 'hour',//小时
  'minute' => 'minute',//分钟
  'this-is-a-public-vote' => 'This is a public vote, other people can see your vote',//(此为公开投票，其他人可看到您的投票项目)
  'submit' => 'submit',//提交
  'reward' => 'reward',//悬赏金额
  'current-state' => 'current state',//当前状态
  'unsolved' => 'unsolved',//未解决
  'resolved' => 'resolved',//已解决
  'best-answer' => 'best answer',//最佳答案
  'view-more' => 'view more',//查看完整内容
  'pro' => 'Pro',//正方观点
  'con' => 'Con',//反方观点
  'people' => 'people',//人
  'publish-opinion' => 'Publish opinion',//发表观点
  'pro-debater' => 'pro debater',//正方辩手
  'con-debater' => 'con debater',//反方辩手
  'judgement' => 'judgment',//裁判
  'end debate' => 'end debate',//结束此次辩论
  'gender' => 'gender',//性别
  'please-use-pc-edition-to-manage-forum-activities' => 'please use PC-edition to manage forum activities',//请您使用非手机版管理活动
  'i-want-to-apply' => 'i want to apply',//我要报名
  'how-to-apply' => 'how to apply',//报名方式
  'attention' => 'attention',//注意
  'this-acticivity-will-deduct-your' => 'this acticivity will deduct your',//参加此活动将扣除您
  'payment-method' => 'payment method',//支付方式
  'bear-your-cost' => 'bear your cost',//承担自己应付的花销
  'pay' => 'pay',//支付
  'leave-a-message' => 'leave a message',//留言
  'posting' => 'posting',//发表帖子
  'posting-a-vote' => 'posting a vote',//发起投票
  'posting-a-reward' => 'posting a reward',//发布悬赏
  'posting-a-debate' => 'posting a debate',//发起辩论
  'posting-a-active' => 'posting a active',//发起活动
  'fill-in-the-title' => 'fill in the title',//请填写标题
  'fill-in-the-content' => 'fill in the content',//请输入内容
  'submit' => 'submit',//发布
  'save' => 'save',//保存
  'save-in-drafts' => 'Save in drafts',//进入草稿箱
  'need-to-fill-in-title-or-content' => 'sorry,you need to fill in the title or content',//抱歉，您尚未输入标题或内容
  'post-has-been-submit' => 'thank you,your post has been submit,please waiting...',//非常感谢，您的主题已发布，现在将转入主题页，请稍候……
  'click-to-return-list' => 'click to return list',//点击这里转入主题列表
  'options' => 'options',//选项
  'please-fill-in-options' => 'options :  items at most',//请填写可投票选项
  'items-at-most' => 'items at most',//最多可选
  'add-1-item' => 'add item',//增加一项
  'voting-results-are-open' => 'voting results are open',//投票后结果可见
  'public-voters' => 'Public voters',//公开投票参与人
  'reward price' => 'reward price',//悬赏价格
  'not-lower-than' => 'not lower  than',//价格不能低于
  'your-points' => 'your points',//您有
  'if-you-dont-set-the-best-answer' => "If you don't set the best answer in 30 days , moderators will set it by their rights.",//30天后如果您仍未设置最佳答案，版主有权代为您选择
  'start-time' => 'start time',//开始时间
  'end-time' => 'end time',//结束时间
  'place' => 'place',//活动地点
  'city' => 'city',//所在城市
  'kind' => ' kind',// 活动类别
  'please-select' => 'please select',//请选择
  'number-of-people' => 'number of people',//需要人数
  'unlimited' => 'Unlimited',//不限
  'male' => 'male',//男
  'female' => 'female',//女
  'required' => 'required',//必填资料项
  'expand' => 'expand',//拓展资料项
  'each-row-represents-a-item' => 'each row represents a item,  iteams at most',//每行代表一个项目，最多3项
  'use-points' => 'use points',//消耗积分
  'cost-per-person' => 'cost per person',//每人花销
  'deadline-for-ajpply' => 'deadline for ajpply',//报名截止
  'activities-pictures' => 'activities pictures',//活动图片
  'post-des' => 'post des',//发帖说明
  'quote' => 'quote',//引用
  'post-chance' => 'post chance',//发帖际遇
  'my-chance-stats' => 'my chance stats',//我的际遇统计
  'times' => 'times',//次
  'reward' => 'reward',//奖励
  'punishment' => 'punishment',//惩罚
  'all-chances' => 'all chances',//所有际遇
  'my-chance' => 'my chance',//我的际遇
  'luck-ranking' => 'luck ranking',//运气排行
  'click-to-view' => 'click to view',//点击查看
  'prev' => 'prev',//上一页
  'next' => 'next',//下一页
  'reward' => 'reward',//奖
  'punishment' => 'punishment',//惩
  'list-of-lucky-people' => 'list of lucky people',//幸运榜
  'list-of-unlucky-people' => 'list of unlucky people',//衰神榜
  'to' => 'to',//到
  'money-unit' => 'dollar',//元
  'the-number-of-registered-followers' => 'the number of registered followers ',//已报名人数
  'remaining-places' => 'remaining places',//剩余名额
  'application-has-been-issued' => 'your application has been issued ,please wait for approval',//您的加入申请已发出，请等待发起者审批
  'you-had-taken-part-in-this-activity' => 'you had taken part in this activity ',//您已经参加了此活动
  'deficiency' => 'deficiency ',//不足
  'cancel-the-registration' => 'cancel the registration',//取消报名
  'proposition' => 'proposition',//正方
  'opposition' => 'opposition',//反方
  'win' => 'win',//赢
  'dogfall' => 'dogfall',//平局
  'time-of-judging' => 'time of judging',//评判时间
  'viewpoint-of-refree' => 'viewpoint of refree',//裁判观点
  'best-debater' => 'best debater',//最佳辩手
  'end-debate' => 'end debate',//结束辩论
  'the-result-is-visible-after-the-vote' => 'the result is visible after the vote',//投票后结果可见
  'the-vote-had-been-over' => 'the vote had been over',//投票已经结束
  'you-dont-have-permission-of-the-vote' => "you don't have permission of the vote",//您没有投票权限
  'your-user-group-has-no-permission-of-the-vote' => 'your user group has no permission of the vote',//您所在的用户组没有投票权限
  'you-had-vote-thanks-for-participation' => 'you had voted，thanks for participation ',//您已经投过票，谢谢您的参与
  'the-voting-lines-had-been-closed-or-out-of-date' => 'the voting lines had been closed or out of date',//该投票已经关闭或者过期，不能投票
  'edit-post-after-checking' => 'edit viewpoint of refree',//编辑裁判观点
  'the-post-is-only-visible-for-author' => 'the post is only visible for author',//此帖仅作者可见
  'a-post-must-be-paied-for-points' => 'a post must be paied for points',//付费主题
  'price' => 'price',//价格
  'home' => 'home',//主页
  'pc' => 'PC'
);

?>